
spring:
  quartz:
    properties:
      org.quartz.scheduler.instanceName: CommentService
      org.quartz.scheduler.instanceId: Comment_1
      org.quartz.jobStore.isClustered: true
      org.quartz.threadPool.threadCount: 3