
#配置数据库账号密码
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_boot
    username: root
    password: root
  output:
    ansi:
      enabled: always

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置mybatis映射文件位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #日志用Slf4j属于接口 实现包可以是logback、log4j SpringBoot内置的是logback

